[package]
name = "felper"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.15"
clap = "4.5.11"
colored = "2.1.0"
dirs = "5.0.1"
predicates = "3.1.2"
tempfile = "3.12.0"
thiserror = "1.0.63"

[dev-dependencies]
anyhow = "1.0.86"
